### ISSUE TITLE
Harvest / Process / Sell

### ISSUE THREAD

**Issue by SLuuuuuuG** [xchopin/FiveM-RP-Boilerplate#10]
Can I disable it so everyone can do most jobs that aren't white-listed without having to be that job at the job center.     Also is it possible to add the police menu (f5) to the CIA job as well.

**Comment by xchopin** [comment]
#### If you want to remove "farming" jobs you can:
- I. Remove them from the job list
- II. Delete the points in the database

#### To have this menu for the CIA you can:
 - I. copy and past the piece of code for the menu in the client file (and changing some pieces of code as well)
- II. add the job ID in the SQL query of the police server file (which can identify who is a cop).

_I would recommend the first option for the CIA which is proper way to do it._

Hope these hints will help you.
