### ISSUE TITLE
yo help me please

### ISSUE THREAD

**Issue by fortniteil** [xchopin/FiveM-RP-Boilerplate#16]
this version on plugins are not the same in the newest version of fivem

can you help me out to get it updated.

**Comment by Jeffixplayer** [comment]
this version on plugins are not the same in the newest version of fivem

can you help me out to get it updated.

**Comment by pjisip** [comment]
![image](https://user-images.githubusercontent.com/39141391/64244619-f7449d80-cf3b-11e9-9f4a-9fe3cdca4e4f.png)
