### ISSUE TITLE
about create account problem

### ISSUE THREAD

**Issue by arliang0415** [xchopin/FiveM-RP-Boilerplate#19]
I try insert data to Mysql, but unsuccessful to connect.
I use Windows 10, FiveM.
Can you teach me how to create account? please.
About using cmd or mysql to create account.
I am not using business, only friends play.

**Comment by xchopin** [comment]
Hi @arliang0415 

So I guess you have something like WAMP installed on your server? 

You have to import the file `install.sql` from your PHPMyAdmin.

Tell me if you need more help.

**Comment by arliang0415** [comment]
![1](https://user-images.githubusercontent.com/50546862/57604540-fe176100-7596-11e9-8e15-3005716781d8.PNG)
![2](https://user-images.githubusercontent.com/50546862/57604541-fe176100-7596-11e9-983d-d8bc45038041.PNG)
![3](https://user-images.githubusercontent.com/50546862/57604542-fe176100-7596-11e9-896d-46f8817f0b26.PNG)
![4](https://user-images.githubusercontent.com/50546862/57604543-feaff780-7596-11e9-9549-d1074e742c36.PNG)



this is my problem.
I need correct create account function.

**Comment by xchopin** [comment]
Okay so it's not a MySQL problem. It means your STEAM_ID is not in the whitelist

**Comment by xchopin** [comment]
Here is the query executed
 ```SQL
SELECT * FROM user_whitelist WHERE identifier = '@username' AND whitelisted = 1;
``` 

you have to add your steam_id to the user_whitelist table

**Comment by arliang0415** [comment]
Thank you for your answer. 
I am already understand how to solve this problem.

**Comment by xchopin** [comment]
Great! I am glad that it's getting solved. 
I am going to close the ticket, if you have other questions do not hesitate to open a new issue.

**Comment by arliang0415** [comment]
Hi,
Do you have legacy version of FiveM?
I don't know what the version i need.

**Comment by xchopin** [comment]
Just download the project it has everything inside

**Comment by arliang0415** [comment]
OK. the client can use the latest version of fivem?

Xavier Chopin <notifications@github.com> 於 2019年5月15日 週三 02:47 寫道：
