### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by KingmanGames** [xchopin/FiveM-RP-Boilerplate#2]
You said languages were easy to change. Not sure where to find that option but I'm going through and translating everything. Nice job though.

**Comment by xchopin** [comment]
Hi, 

I meant it's easy texts to translate. In resources, you have to open each directory and translate the server and client files

**Comment by KingmanGames** [comment]
Ah, yeah I got you. 
Already started 👍 

Another issue is the DB. After importing I get an error: /* SQL Error (1075): Incorrect table definition; there can be only one auto column and it must be defined as a key */ 
Could you help out with this?

**Comment by xchopin** [comment]
Just tried to import the SQL file I don't get errors. Which version of MySQL are you using?

**Comment by KingmanGames** [comment]
I'm using 10.1.21-MariaDB

**Comment by xchopin** [comment]
I have to try on my Arch Linux.
It's because of the job name, the SQL query to check if you're a cop is kind of
`SELECT job_name [...] WHERE job_name LIKE 'LSPD%`

It means your police job name has to start with 'LSPD' in the database, else change the SQL query

**Comment by KingmanGames** [comment]
I dont mean to keep bothering you but you are helping me out alot and I appreciate it! But I'm not too familiar with SQL related things, this is what the query for 'jobs' looks like right now. (same as the version you released)

`CREATE TABLE `jobs` (
  `job_id` int(11) NOT NULL,
  `job_name` varchar(40) NOT NULL,
  `salary` int(11) NOT NULL DEFAULT '500',
  `whitelisted` tinyint(4) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `jobs`
--

INSERT INTO `jobs` (`job_id`, `job_name`, `salary`, `whitelisted`) VALUES
(1, 'Chômeur', 200, 0),
(2, 'LSPD (Cadet)', 450, 1),
(3, 'LSPD (Officier)', 750, 1),
(4, 'LSPD (Sergent)', 1000, 1),
(5, 'LSPD (Commandant)', 1600, 1),
(6, 'CHU (Interne)', 400, 1),
(7, 'CHU (Médecin)', 850, 1),
(8, 'CHU (Chef de service)', 900, 1),
(9, 'CHU (Directeur)', 2700, 1),
(10, 'GSPR 1', 2200, 1),
(11, 'GSPR 2', 3200, 1),
(12, 'GSPR 3', 4800, 1),
(13, 'Gouverneur', 5000, 1),
(14, 'Ministre de l\'Économie', 3000, 1),
(15, 'Ministre de l\'Intérieur', 3000, 1),
(16, 'Ministre de la Communication', 3000, 1),
(17, 'Bûcheron', 90, 0),
(18, 'Viticulteur', 75, 0),
(19, 'Mineur', 75, 0),
(20, 'Illegal', 0, 0),
(21, 'Livreur', 75, 0),
(22, 'Taxi', 90, 0),
(23, 'Juge', 1300, 1),
(24, 'Avocat', 1000, 1);`

**Comment by xchopin** [comment]
Did you translate the jobs name or they have the original name?

**Comment by KingmanGames** [comment]
It's all original. 
Do you want to add me on steam so it's easier to talk?

**Comment by xchopin** [comment]
I don't have Steam on my discord, I have Skype (old af) if you want to text

**Comment by KingmanGames** [comment]
I'll do Skype 👍

**Comment by KingmanGames** [comment]
my skype is: mitchellstartsfires
