### ISSUE TITLE
Your server on zaphosting 

### ISSUE THREAD

**Issue by Andripili** [xchopin/FiveM-RP-Boilerplate#20]
I found your fiveM server package on github; I wouldn't want to host it from my pc but using zap hosting could you help me?

**Comment by ZonEmOToRY** [comment]
Hey Man is it working for you ?

**Comment by xchopin** [comment]
Yes it is possible to host it on a dedicated server, but it has nothing to do with this github project, it's all about sysadmin things (I mean it's kind of explained in the README file)
