### ISSUE TITLE
version

### ISSUE THREAD

**Issue by Exu9x** [xchopin/FiveM-RP-Boilerplate#22]
windows server or linux?

**Comment by xchopin** [comment]
@Exu9x both!

**Comment by Exu9x** [comment]
When un tryin to open run.bat citizen closes instantly

Xavier Chopin <notifications@github.com> (šajā datumā: Ot, 2019. g. 12.
nov. 15:29) rakstīja:

**Comment by Exu9x** [comment]
Server files are too old, how to upgrade and which files i need to upgrade?

**Comment by xchopin** [comment]
.bat is for windows .sh is for linux systems

I don't know it's written that I do not maintain the project anymore sorry

**Comment by Exu9x** [comment]
Ye,  but how to update server files?

Xavier Chopin <notifications@github.com> (šajā datumā: Tr, 2019. g. 13.
nov. 17:36) rakstīja:
