### ISSUE TITLE
Help me please.  

### ISSUE THREAD

**Issue by hmathir** [xchopin/FiveM-RP-Boilerplate#23]
I import install.sql and copy all resource to my resources directory . after that from [jobs], [car] i also copy sub resources like police,minor and also put that on resources directory.
That's mean, from  ("resource/[jobs]/police") to ("resources/police") but what's next? When i open server.lua i found localhost. I have to put ex: "localhost:5977"???  Is it?

**Comment by craztheking** [comment]
Readme:
Warning: This project is not maintained anymore and uses the legacy version of FiveM

**Comment by xchopin** [comment]
if your MySQL/MariaDB is installed on the 5977 port, then yes
(cf: https://github.com/xchopin/FiveM-RP-Boilerplate/blob/master/resources/essentialmode/lib/MySQL.lua)

I advice you to use the default port which is 3306, to make it easier tho (you would have to type 'localhost' only without the port)
