### ISSUE TITLE
so the jobs dont seem to work you got to the wood area nothing happens

### ISSUE THREAD

**Issue by haydo1997** [xchopin/FiveM-RP-Boilerplate#3]
so the jobs dont seem to work you got to the wood area nothing happens

**Comment by xchopin** [comment]
Did you change the job id in the database?

**Comment by haydo1997** [comment]
no

**Comment by haydo1997** [comment]
nothing change uploaded and test and no jobs are working

**Comment by xchopin** [comment]
that's weird because it worked for everyone else. I will check later

**Comment by haydo1997** [comment]
also the map not loading es free-room to i had to fix that

**Comment by xchopin** [comment]
Just tried, everything works. You don't give me more details about errors I close the topic.

**Comment by haydo1997** [comment]
so you can gather wood and that
