### ISSUE TITLE
Screen Fade interfering with script.

### ISSUE THREAD

**Issue by VacEx0** [xchopin/FiveM-RP-Boilerplate#31]
I was making a script recently that used `DoScreenFadeIn` and `DoScreenFadeOut` with the loading screen. **spawnmanager** was using these natives as well as `IsScreenFadedIn` and `IsScreenFadedOut` in a loop to finish spawning the player. My script needed to fade the screen out when the player spawned and keep it like that for a certain period of time, however when **spawnmanager** detected that in its loop the `PlayerSpawned` event was fired multiple times and the screen fade I had was removed. This caused complications with my script.

I found a solution though, but I had to manually modify **spawnmanager.lua**. Was wondering if there is a way to easily disable screen fading completely from **spawnmanager** within other scripts so that we dont have to modify the code from another resource to get it working.

**Comment by xchopin** [comment]
Hi @VacEx0 please check the license for spawnmanager I am not the author of this one; thanks for the feedback though.

**Comment by VacEx0** [comment]
> Hi @VacEx0 please check the license for spawnmanager I am not the author of this one; thanks for the feedback though.

My bad, thank you though.
