### ISSUE TITLE
How would i go about whitelisting police and ems?

### ISSUE THREAD

**Issue by JakeRyan1** [xchopin/FiveM-RP-Boilerplate#7]

**Comment by xchopin** [comment]
You have to set the job to people you want through your DBMS

**Comment by JakeRyan1** [comment]
So why would i do that if they want to do another job they can then i have to do it again

**Comment by xchopin** [comment]
If you want to add someone in the LSPD/Government/EMS you have to do it with the DBMS else they can do it alone at the "Pole Emploi"'s blip

 Else you remove the whitelist but it might screw up the roleplay on your server

**Comment by JakeRyan1** [comment]
So under whitelist in the database i need to give them the role to use it?
Can they go on other jobs or just the one that i have set them to?

**Comment by joaocarlospt** [comment]
how do i give me admin?

**Comment by SLuuuuuuG** [comment]
How do I access the police menu?    Do you have a garage for police vehicles as well?   It appears to be built into the code but I cant see the commands.   Loving the package though!! NICELY DONE
