### ISSUE TITLE
FXServer ?

### ISSUE THREAD

**Issue by wesleymoura** [xchopin/FiveM-RP-Boilerplate#9]
Will be converted to fxserver?

**Comment by xchopin** [comment]
Hi,
sorry I didn't check the FiveM updates. Is it their new server application ?

**Comment by wesleymoura** [comment]
Yes, FXServer will be the new structure, the current Citizen MP starting from the 15th, FiveM will not support it anymore, more infos https://forum.fivem.net/t/deprecating-citizenmp-server/36810
